# Generated by Django 5.0.6 on 2024-05-15 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_fixedmaterial_fixedchatmessage_prompt_fixedinput_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='backend.topic'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['parent'], name='backend_top_parent__a40e4c_idx'),
        ),
    ]
