# Generated by Django 5.0.6 on 2024-05-30 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_topic_parent_topic_backend_top_parent__a40e4c_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chat',
            name='backend_cha_mode_987a2f_idx',
        ),
        migrations.AddField(
            model_name='chat',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.material'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sequence',
            field=models.PositiveIntegerField(default=1, verbose_name='Sequence of the message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixedchatmessage',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.chat'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['mode', 'topic', 'material'], name='backend_cha_mode_c675ab_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'sequence'], name='backend_cha_chat_id_518171_idx'),
        ),
    ]
