# Generated by Django 5.0.6 on 2024-05-31 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_chat_backend_cha_mode_987a2f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaterial',
            name='easiness',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='usermaterial',
            name='interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usermaterial',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermaterial',
            name='learned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermaterial',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usermaterial',
            name='repetition',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
