# Generated by Django 5.0.6 on 2024-06-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_usermaterial_easiness_usermaterial_interval_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='prompt',
            name='backend_pro_materia_05ff7a_idx',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='material',
        ),
        migrations.AddField(
            model_name='prompt',
            name='name',
            field=models.CharField(default='no', max_length=50, verbose_name='The name of the prompt.'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['name', 'editable'], name='backend_pro_name_c5f6cf_idx'),
        ),
    ]
